upstream dotnet_backend {
    server sandbox-dotnet-backend.onrender.com:443;
    server sandbox-dotnet-backend-1.onrender.com:443;
    server sandbox-dotnet-backend-2.onrender.com:443;
}

server {
    listen 80;

    location /ping {
        proxy_pass https://dotnet_backend;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_ssl_server_name on;
        proxy_redirect off;
    }

    location / {
        proxy_pass https://dotnet_backend;   # changed to HTTPS
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_ssl_server_name on;
        proxy_redirect off;
    }
}
